In [1]:
l1 = [10, 20.67,"abc", False]

In [2]:
l1

[10, 20.67, 'abc', False]

In [3]:
# alist accepts data of all datatypes

In [4]:
import numpy as np

In [6]:
a1 = np.array(l1)

In [7]:
a1

array(['10', '20.67', 'abc', 'False'],
      dtype='<U32')

In [8]:
# array can accomodate values of same datatype from the eg 
# still numpy arrays are of more use as numpy arrays have versatile and powerful functions which has many uses
# l1. (press tab)it wil lists  all functions available for computing.
# a1. (press tab) more fucntions available for computation.
# matrices are 2D arrays

#---------------------------------------------
# while slicing arrays its a view of the original array we work with, not a copy
# numpy protects the memory space by this, avoiding creating many small arrays
# to make a copy of the array , use copy function.

In [9]:
l2 = [123, 340.5,True]

In [10]:
a2 = np.array(l2)

In [11]:
a2

array([ 123. ,  340.5,    1. ])

In [12]:
a3 = np.array([1000,6000,8000,True])

In [13]:
a3

array([1000, 6000, 8000,    1])

In [15]:
a3.mean()

3750.25

In [17]:
l2.pop() # pop fn pops out the last value

True

In [18]:
l2

[123, 340.5]

In [23]:
l2.reverse()

In [22]:
l2 

[123, 340.5]

In [25]:
l2.append(50)

In [26]:
l2

[340.5, 123, 50]

In [30]:
l2.count(1)

0

In [32]:
a5 = np.array([500,600,-200,-300,100,450,670])

In [33]:
a5

array([ 500,  600, -200, -300,  100,  450,  670])

In [34]:
a5[2:]

array([-200, -300,  100,  450,  670])

In [35]:
a5

array([ 500,  600, -200, -300,  100,  450,  670])

In [36]:
a5[2:6]

array([-200, -300,  100,  450])

In [42]:
b= a5[2:4]

In [43]:
b

array([-200, -300])

In [44]:
b[:] =750

In [45]:
b

array([750, 750])

In [46]:
a5

array([500, 600, 750, 750, 100, 450, 670])

In [47]:
c = a5.copy()

In [48]:
c

array([500, 600, 750, 750, 100, 450, 670])

In [49]:
c[1] = 220

In [50]:
c 

array([500, 220, 750, 750, 100, 450, 670])

In [51]:
a5

array([500, 600, 750, 750, 100, 450, 670])